-- ===========================================================================
-- Author:          Vairavan Chandrasekhar
-- File Name:        BACKOUT_DDL_DML_BATCH_DB_08012019-01.sql
-- Create date:     06/02/2019
-- Description:     Back out Script to drop the tablespace
-- ===========================================================================

 

DROP TRIGGER DEV_FED.TRG_TBLALLOWDENYMATCHING1;
DROP TRIGGER DEV_FED.TRG_TBLAPPLICATIONS1;
DROP TRIGGER DEV_FED.TRG_TBLCLIENTCOMM1;
DROP TRIGGER DEV_FED.TRG_TBLCLIENTENROLLMENT1;
DROP TRIGGER DEV_FED.TRG_TBLDESTTYPES1;
DROP TRIGGER DEV_FED.TRG_TBLOPTIONS1;
DROP TRIGGER DEV_FED.TRG_TBLPRODUCTS1;
DROP TRIGGER DEV_FED.TRG_TBLSOURCETYPES1;
DROP TRIGGER DEV_FED.TRG_TBLDESTCOMM1;
DROP TRIGGER DEV_FED.TRG_TBLDESTENROLLMENT1;

 

DROP TABLE DEV_FED.TBLALLOWDENYMATCHING;
DROP TABLE DEV_FED.TBLCLIENTCOMM;
DROP TABLE DEV_FED.TBLCLIENTENROLLMENT;
DROP TABLE DEV_FED.TBLDESTTYPES;
DROP TABLE DEV_FED.TBLPRODUCTS;
DROP TABLE DEV_FED.TBLSOURCETYPES;
DROP TABLE DEV_FED.TBLAPPLICATIONS;
DROP TABLE DEV_FED.TBLDESTCOMM;
DROP TABLE DEV_FED.TBLDESTENROLLMENT;
DROP TABLE DEV_FED.TBLOPTIONS;

 

DROP PROCEDURE DEV_FED.GETBBSID; 
DROP PROCEDURE DEV_FED.GETCLIENTSTATUS;
DROP PACKAGE BODY DEV_FED.LANG_INTEGER;
DROP PACKAGE DEV_FED.LANG_INTEGER;
