SELECT CASE 
	WHEN rec_ins_cnt = 1 
	THEN 'ALL RECORDS GOT INSERTED SUCCESSFULLY'
		ELSE 'INSERTED RECORDS MISSING, VERIFICATION FAILED'
	END AS status
	FROM (
		SELECT  COUNT(*) AS rec_ins_cnt
		FROM EDI.CODE_VALUE WHERE VALUE_CDF_MEANING = 'INFORMATION' AND CODE_SET = ( SELECT CODE_SET FROM EDI.CODE_SET WHERE CODE_SET_NAME = 'TRACKING_EVENT_TYPE' ));
