SELECT CASE 
	WHEN rec_ins_cnt = 1 
	THEN 'ALL RECORDS GOT INSERTED SUCCESSFULLY'
		ELSE 'INSERTED RECORDS MISSING, VERIFICATION FAILED'
	END AS status
	FROM (
		SELECT  COUNT(*) AS rec_ins_cnt
		FROM EDI.CODE_VALUE WHERE VALUE_CDF_MEANING = 'EPAYMENT_RECON_JENKINS_SAMPLE' );
